import { Inter_Tight } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TranslationsProvider from '@/contexts/TranslationsProvider';
import initTranslations from '../i18n';

const roboto = Inter_Tight({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const i18Namespaces = ['home'];

export default async function RootLayout({
  params: { locale },
  children,
}: Readonly<{
  params: any;
  children: React.ReactNode;
}>) {
  const { resources } = await initTranslations(locale, i18Namespaces);

  return (
    <html lang="en">
      <body
        className={`${roboto.className} container mx-auto max-w-[640px] overflow-x-hidden bg-mainback sm:max-w-[1920px]`}
      >
        <div
          style={{
            width: 'calc(100vw - 10%);',
          }}
          className="mx-auto flex min-h-screen flex-col justify-center sm:w-1"
        >
          <Header />
          <TranslationsProvider
            resources={resources}
            locale={locale}
            namespaces={i18Namespaces}
          >
            <main className="mt-56 flex grow flex-col items-center justify-center gap-[100px] sm:gap-[220px]">
              {children}
            </main>
          </TranslationsProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
